baseURL = "https://csitauthority.github.io/6thSem"
languageCode = "en-US"
defaultContentLanguage = "en"
publishDir="docs"
title = "6th Sem CSITauthority"
theme = "csitauthority-learn"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

# Enable comments by entering your Disqus shortname
disqusShortname = "csitauthority"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-75904987-1"

[params]
  editURL = "https://github.com/csitauthority/6thSem/edit/master/content/"
  uploadURL = "https://github.com/csitauthority/6thSem/upload/master/content/"
  description = "6th Semester Contents for BSc. CSIT"
  repoView = "https://github.com/csitauthority/6thSem"
  repoStar = "https://github.com/csitauthority/6thSem"
  repoFork = "https://github.com/csitauthority/6thSem/fork"
  author = "CSITauthority"
  showVisitedLinks = true
  disableLanguageSwitchingButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "CSITauthority 6th Sem"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-home'></i> Homepage"
url = "../.."
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-code-fork'></i> Contribute"
url = "how-to-contribute"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "credits"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-file-text'></i> License"
url = "https://github.com/csitauthority/6thSem/blob/master/LICENSE"
weight = 50

[Languages.np]
title = "CSITauthority 6th Sem"
weight = 2
languageName = "नेपाली"

[[Languages.np.menu.shortcuts]]
name = "<i class='fa fa-home'></i> गृहपृष्ठ"
url = "../.."
weight = 20

[[Languages.np.menu.shortcuts]]
name = "<i class='fa fa-code-fork'></i> तपाईको योगदान"
url = "../en/how-to-contribute"
weight = 30

[[Languages.np.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> श्रेय​"
url = "../../6thSem/en/credits/"
weight = 40

[[Languages.np.menu.shortcuts]]
name = "<i class='fa fa-file-text'></i> अनुमतिपत्र​"
url = "https://github.com/csitauthority/6thSem/blob/master/LICENSE"
weight = 50